#!/bin/bash

#SBATCH -J 2-lme-female
#SBATCH --time=36:00:00
#SBATCH -p cclake-himem
#SBATCH --cpus-per-task=6
#SBATCH --mail-type=ALL
#SBATCH --array=50,60

#SBATCH -o slurm_log/slurm-%x_%a.out
#SBATCH -A mrc-bsu-sl2-cpu

. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4                   # REQUIRED - loads the basic environment
module load R/4.2.0

Rscript 2_lmfit_5outcomes_RIRS_ZG.R $SLURM_ARRAY_TASK_ID "female"
