#!/bin/bash

#SBATCH -J 3_1-riskratio
#SBATCH --time=4:00:00
#SBATCH -p icelake-himem
#SBATCH -c 8
#SBATCH --mail-type=ALL
#SBATCH --array=1

#SBATCH -o slurm_log/slurm-%x_%a.out
#SBATCH -A mrc-bsu-sl2-cpu

. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4                   # REQUIRED - loads the basic environment
module load R/4.3.1-icelake

Rscript 3_1_prediction_5y_10y_relation.R