#!/bin/bash

#SBATCH -J 4-cstime
#SBATCH --time=2:00:00
#SBATCH -p cclake-himem
#SBATCH -c 2
#SBATCH --mail-type=ALL
#SBATCH --array=40-80:5

#SBATCH -o slurm_log/slurm-%x_%a.out
#SBATCH -A mrc-bsu-sl2-cpu

. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4                   # REQUIRED - loads the basic environment
module load R/4.2.0

Rscript 4_optimal_screening_CVD_ZG.R $SLURM_ARRAY_TASK_ID "male"
Rscript 4_optimal_screening_CVD_ZG.R $SLURM_ARRAY_TASK_ID "female"